var syscalls_x86_64 = {
   "aaData": [
      [
         0,
         "sys_read",
         "(int fd,void * buf,size_t len)",
         "0x0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         1,
         "sys_write",
         "not found",
         "0x1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         2,
         "sys_open",
         "not found",
         "0x2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         3,
         "sys_close",
         "not found",
         "0x3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         4,
         "sys_newstat",
         "not found",
         "0x4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         5,
         "sys_newfstat",
         "not found",
         "0x5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         6,
         "sys_newlstat",
         "not found",
         "0x6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         7,
         "sys_poll",
         "not found",
         "0x7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         8,
         "sys_lseek",
         "not found",
         "0x8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         9,
         "sys_mmap",
         "(unsigned long addr,unsigned long len,unsigned long prot,unsigned long flags,unsigned long fd,unsigned long offset)",
         "0x9",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/arch/x86/kernel/sys_x86_64.c",
         82
      ],
      [
         10,
         "sys_mprotect",
         "(void * ptr,size_t size,unsigned long prot)",
         "0xa",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         11,
         "sys_munmap",
         "(void * ptr,size_t size)",
         "0xb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         12,
         "sys_brk",
         "not found",
         "0xc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         13,
         "sys_rt_sigaction",
         "not found",
         "0xd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         14,
         "sys_rt_sigprocmask",
         "not found",
         "0xe",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         15,
         "sys_rt_sigreturn",
         "(struct pt_regs * regs)",
         "0xf",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/arch/x86/kernel/signal_64.c",
         246
      ],
      [
         16,
         "sys_ioctl",
         "not found",
         "0x10",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         17,
         "sys_pread64",
         "not found",
         "0x11",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         18,
         "sys_pwrite64",
         "not found",
         "0x12",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         19,
         "sys_readv",
         "not found",
         "0x13",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         20,
         "sys_writev",
         "not found",
         "0x14",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         21,
         "sys_access",
         "not found",
         "0x15",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         22,
         "sys_pipe",
         "not found",
         "0x16",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         23,
         "sys_select",
         "not found",
         "0x17",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         24,
         "sys_sched_yield",
         "not found",
         "0x18",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         25,
         "sys_mremap",
         "(void * addr,size_t old_len,size_t new_len,unsigned long flags,void * new_addr)",
         "0x19",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         26,
         "sys_msync",
         "not found",
         "0x1a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         27,
         "sys_mincore",
         "not found",
         "0x1b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         28,
         "sys_madvise",
         "(void * start,size_t len,int types)",
         "0x1c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         29,
         "sys_shmget",
         "not found",
         "0x1d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         30,
         "sys_shmat",
         "not found",
         "0x1e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         31,
         "sys_shmctl",
         "not found",
         "0x1f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         32,
         "sys_dup",
         "not found",
         "0x20",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         33,
         "sys_dup2",
         "not found",
         "0x21",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         34,
         "sys_pause",
         "not found",
         "0x22",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         35,
         "sys_nanosleep",
         "not found",
         "0x23",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         36,
         "sys_getitimer",
         "not found",
         "0x24",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         37,
         "sys_alarm",
         "not found",
         "0x25",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         38,
         "sys_setitimer",
         "not found",
         "0x26",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         39,
         "sys_getpid",
         "not found",
         "0x27",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         40,
         "sys_sendfile64",
         "not found",
         "0x28",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         41,
         "sys_socket",
         "not found",
         "0x29",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         42,
         "sys_connect",
         "not found",
         "0x2a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         43,
         "sys_accept",
         "not found",
         "0x2b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         44,
         "sys_sendto",
         "not found",
         "0x2c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         45,
         "sys_recvfrom",
         "not found",
         "0x2d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         46,
         "sys_sendmsg",
         "not found",
         "0x2e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         47,
         "sys_recvmsg",
         "not found",
         "0x2f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         48,
         "sys_shutdown",
         "not found",
         "0x30",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         49,
         "sys_bind",
         "not found",
         "0x31",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         50,
         "sys_listen",
         "not found",
         "0x32",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         51,
         "sys_getsockname",
         "not found",
         "0x33",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         52,
         "sys_getpeername",
         "not found",
         "0x34",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         53,
         "sys_socketpair",
         "not found",
         "0x35",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         54,
         "sys_setsockopt",
         "not found",
         "0x36",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         55,
         "sys_getsockopt",
         "not found",
         "0x37",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         56,
         "sys_clone",
         "(unsigned long clone_flags,unsigned long newsp,int * parent_tidptr,unsigned long tls,int * child_tidptr)",
         "0x38",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/fork.c",
         2888
      ],
      [
         57,
         "sys_fork",
         "not found",
         "0x39",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         58,
         "sys_vfork",
         "not found",
         "0x3a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         59,
         "sys_execve",
         "not found",
         "0x3b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         60,
         "sys_exit",
         "(struct syscall_exit_args * args)",
         "0x3c",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/exit.c",
         1067
      ],
      [
         61,
         "sys_wait4",
         "not found",
         "0x3d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         62,
         "sys_kill",
         "not found",
         "0x3e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         63,
         "sys_newuname",
         "not found",
         "0x3f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         64,
         "sys_semget",
         "not found",
         "0x40",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         65,
         "sys_semop",
         "not found",
         "0x41",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         66,
         "sys_semctl",
         "not found",
         "0x42",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         67,
         "sys_shmdt",
         "not found",
         "0x43",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         68,
         "sys_msgget",
         "not found",
         "0x44",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         69,
         "sys_msgsnd",
         "not found",
         "0x45",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         70,
         "sys_msgrcv",
         "not found",
         "0x46",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         71,
         "sys_msgctl",
         "not found",
         "0x47",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         72,
         "sys_fcntl",
         "not found",
         "0x48",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         73,
         "sys_flock",
         "not found",
         "0x49",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         74,
         "sys_fsync",
         "not found",
         "0x4a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         75,
         "sys_fdatasync",
         "not found",
         "0x4b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         76,
         "sys_truncate",
         "not found",
         "0x4c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         77,
         "sys_ftruncate",
         "not found",
         "0x4d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         78,
         "sys_getdents",
         "not found",
         "0x4e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         79,
         "sys_getcwd",
         "not found",
         "0x4f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         80,
         "sys_chdir",
         "not found",
         "0x50",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         81,
         "sys_fchdir",
         "not found",
         "0x51",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         82,
         "sys_rename",
         "not found",
         "0x52",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         83,
         "sys_mkdir",
         "not found",
         "0x53",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         84,
         "sys_rmdir",
         "not found",
         "0x54",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         85,
         "sys_creat",
         "not found",
         "0x55",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         86,
         "sys_link",
         "not found",
         "0x56",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         87,
         "sys_unlink",
         "not found",
         "0x57",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         88,
         "sys_symlink",
         "not found",
         "0x58",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         89,
         "sys_readlink",
         "not found",
         "0x59",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         90,
         "sys_chmod",
         "not found",
         "0x5a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         91,
         "sys_fchmod",
         "not found",
         "0x5b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         92,
         "sys_chown",
         "not found",
         "0x5c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         93,
         "sys_fchown",
         "not found",
         "0x5d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         94,
         "sys_lchown",
         "not found",
         "0x5e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         95,
         "sys_umask",
         "not found",
         "0x5f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         96,
         "sys_gettimeofday",
         "(struct timeval * tv,struct timezone * tz)",
         "0x60",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/time/time.c",
         224
      ],
      [
         97,
         "sys_getrlimit",
         "not found",
         "0x61",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         98,
         "sys_getrusage",
         "not found",
         "0x62",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         99,
         "sys_sysinfo",
         "not found",
         "0x63",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         100,
         "sys_times",
         "not found",
         "0x64",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         101,
         "sys_ptrace",
         "(long request,pid_t pid,unsigned long addr,unsigned long data)",
         "0x65",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/ptrace.c",
         1526
      ],
      [
         102,
         "sys_getuid",
         "not found",
         "0x66",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         103,
         "sys_syslog",
         "not found",
         "0x67",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         104,
         "sys_getgid",
         "not found",
         "0x68",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         105,
         "sys_setuid",
         "not found",
         "0x69",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         106,
         "sys_setgid",
         "not found",
         "0x6a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         107,
         "sys_geteuid",
         "not found",
         "0x6b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         108,
         "sys_getegid",
         "not found",
         "0x6c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         109,
         "sys_setpgid",
         "not found",
         "0x6d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         110,
         "sys_getppid",
         "not found",
         "0x6e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         111,
         "sys_getpgrp",
         "not found",
         "0x6f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         112,
         "sys_setsid",
         "not found",
         "0x70",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         113,
         "sys_setreuid",
         "not found",
         "0x71",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         114,
         "sys_setregid",
         "not found",
         "0x72",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         115,
         "sys_getgroups",
         "not found",
         "0x73",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         116,
         "sys_setgroups",
         "not found",
         "0x74",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         117,
         "sys_setresuid",
         "not found",
         "0x75",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         118,
         "sys_getresuid",
         "not found",
         "0x76",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         119,
         "sys_setresgid",
         "not found",
         "0x77",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         120,
         "sys_getresgid",
         "not found",
         "0x78",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         121,
         "sys_getpgid",
         "not found",
         "0x79",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         122,
         "sys_setfsuid",
         "not found",
         "0x7a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         123,
         "sys_setfsgid",
         "not found",
         "0x7b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         124,
         "sys_getsid",
         "not found",
         "0x7c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         125,
         "sys_capget",
         "not found",
         "0x7d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         126,
         "sys_capset",
         "not found",
         "0x7e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         127,
         "sys_rt_sigpending",
         "not found",
         "0x7f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         128,
         "sys_rt_sigtimedwait",
         "not found",
         "0x80",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         129,
         "sys_rt_sigqueueinfo",
         "(pid_t tgid,int sig,siginfo_t * uinfo)",
         "0x81",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/signal.c",
         4222
      ],
      [
         130,
         "sys_rt_sigsuspend",
         "not found",
         "0x82",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         131,
         "sys_sigaltstack",
         "not found",
         "0x83",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         132,
         "sys_utime",
         "not found",
         "0x84",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         133,
         "sys_mknod",
         "not found",
         "0x85",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         135,
         "sys_personality",
         "not found",
         "0x87",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         136,
         "sys_ustat",
         "not found",
         "0x88",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         137,
         "sys_statfs",
         "not found",
         "0x89",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         138,
         "sys_fstatfs",
         "not found",
         "0x8a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         139,
         "sys_sysfs",
         "not found",
         "0x8b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         140,
         "sys_getpriority",
         "not found",
         "0x8c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         141,
         "sys_setpriority",
         "not found",
         "0x8d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         142,
         "sys_sched_setparam",
         "not found",
         "0x8e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         143,
         "sys_sched_getparam",
         "not found",
         "0x8f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         144,
         "sys_sched_setscheduler",
         "not found",
         "0x90",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         145,
         "sys_sched_getscheduler",
         "not found",
         "0x91",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         146,
         "sys_sched_get_priority_max",
         "not found",
         "0x92",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         147,
         "sys_sched_get_priority_min",
         "not found",
         "0x93",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         148,
         "sys_sched_rr_get_interval",
         "not found",
         "0x94",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         149,
         "sys_mlock",
         "not found",
         "0x95",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         150,
         "sys_munlock",
         "not found",
         "0x96",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         151,
         "sys_mlockall",
         "not found",
         "0x97",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         152,
         "sys_munlockall",
         "not found",
         "0x98",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         153,
         "sys_vhangup",
         "not found",
         "0x99",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         154,
         "sys_modify_ldt",
         "not found",
         "0x9a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         155,
         "sys_pivot_root",
         "not found",
         "0x9b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         156,
         "sys_ni_syscall",
         "(void)",
         "0x9c",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/arch/x86/kernel/process.c",
         1086
      ],
      [
         157,
         "sys_prctl",
         "not found",
         "0x9d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         158,
         "sys_arch_prctl",
         "not found",
         "0x9e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         159,
         "sys_adjtimex",
         "not found",
         "0x9f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         160,
         "sys_setrlimit",
         "not found",
         "0xa0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         161,
         "sys_chroot",
         "not found",
         "0xa1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         162,
         "sys_sync",
         "not found",
         "0xa2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         163,
         "sys_acct",
         "not found",
         "0xa3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         164,
         "sys_settimeofday",
         "not found",
         "0xa4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         165,
         "sys_mount",
         "(const char * dev_name,const char * dir_name,const char * type,unsigned long flags,const void * data)",
         "0xa5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         166,
         "sys_umount",
         "not found",
         "0xa6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         167,
         "sys_swapon",
         "not found",
         "0xa7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         168,
         "sys_swapoff",
         "not found",
         "0xa8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         169,
         "sys_reboot",
         "not found",
         "0xa9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         170,
         "sys_sethostname",
         "not found",
         "0xaa",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         171,
         "sys_setdomainname",
         "not found",
         "0xab",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         172,
         "sys_iopl",
         "not found",
         "0xac",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         173,
         "sys_ioperm",
         "not found",
         "0xad",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         175,
         "sys_init_module",
         "not found",
         "0xaf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         176,
         "sys_delete_module",
         "not found",
         "0xb0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         179,
         "sys_quotactl",
         "not found",
         "0xb3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         186,
         "sys_gettid",
         "not found",
         "0xba",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         187,
         "sys_readahead",
         "not found",
         "0xbb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         188,
         "sys_setxattr",
         "not found",
         "0xbc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         189,
         "sys_lsetxattr",
         "not found",
         "0xbd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         190,
         "sys_fsetxattr",
         "not found",
         "0xbe",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         191,
         "sys_getxattr",
         "not found",
         "0xbf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         192,
         "sys_lgetxattr",
         "not found",
         "0xc0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         193,
         "sys_fgetxattr",
         "not found",
         "0xc1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         194,
         "sys_listxattr",
         "not found",
         "0xc2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         195,
         "sys_llistxattr",
         "not found",
         "0xc3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         196,
         "sys_flistxattr",
         "not found",
         "0xc4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         197,
         "sys_removexattr",
         "not found",
         "0xc5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         198,
         "sys_lremovexattr",
         "not found",
         "0xc6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         199,
         "sys_fremovexattr",
         "not found",
         "0xc7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         200,
         "sys_tkill",
         "not found",
         "0xc8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         201,
         "sys_time",
         "(time_t * t)",
         "0xc9",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/sys.c",
         1083
      ],
      [
         202,
         "sys_futex",
         "(void * addr1,int op,int val1,struct timespec * timeout,void * addr2,int val3)",
         "0xca",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/futex/syscalls.c",
         414
      ],
      [
         203,
         "sys_sched_setaffinity",
         "(pid_t pid,unsigned int len,unsigned long * m)",
         "0xcb",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/compat.c",
         124
      ],
      [
         204,
         "sys_sched_getaffinity",
         "(pid_t pid,unsigned int len,unsigned long * m)",
         "0xcc",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/compat.c",
         144
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         206,
         "sys_io_setup",
         "not found",
         "0xce",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         207,
         "sys_io_destroy",
         "not found",
         "0xcf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         208,
         "sys_io_getevents",
         "not found",
         "0xd0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         209,
         "sys_io_submit",
         "not found",
         "0xd1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         210,
         "sys_io_cancel",
         "not found",
         "0xd2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         213,
         "sys_epoll_create",
         "not found",
         "0xd5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         216,
         "sys_remap_file_pages",
         "not found",
         "0xd8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         217,
         "sys_getdents64",
         "not found",
         "0xd9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         218,
         "sys_set_tid_address",
         "not found",
         "0xda",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         219,
         "sys_restart_syscall",
         "not found",
         "0xdb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         220,
         "sys_semtimedop",
         "not found",
         "0xdc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         221,
         "sys_fadvise64",
         "not found",
         "0xdd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         222,
         "sys_timer_create",
         "not found",
         "0xde",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         223,
         "sys_timer_settime",
         "not found",
         "0xdf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         224,
         "sys_timer_gettime",
         "not found",
         "0xe0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         225,
         "sys_timer_getoverrun",
         "not found",
         "0xe1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         226,
         "sys_timer_delete",
         "not found",
         "0xe2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         227,
         "sys_clock_settime",
         "not found",
         "0xe3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         228,
         "sys_clock_gettime",
         "(clockid_t id,struct timespec * ts)",
         "0xe4",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/time/posix-stubs.c",
         60
      ],
      [
         229,
         "sys_clock_getres",
         "not found",
         "0xe5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         230,
         "sys_clock_nanosleep",
         "not found",
         "0xe6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         231,
         "sys_exit_group",
         "not found",
         "0xe7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         232,
         "sys_epoll_wait",
         "not found",
         "0xe8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         233,
         "sys_epoll_ctl",
         "not found",
         "0xe9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         234,
         "sys_tgkill",
         "not found",
         "0xea",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         235,
         "sys_utimes",
         "not found",
         "0xeb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         "",
         "not implemented",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         "",
         ""
      ],
      [
         237,
         "sys_mbind",
         "not found",
         "0xed",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         238,
         "sys_set_mempolicy",
         "not found",
         "0xee",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         239,
         "sys_get_mempolicy",
         "not found",
         "0xef",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         240,
         "sys_mq_open",
         "not found",
         "0xf0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         241,
         "sys_mq_unlink",
         "not found",
         "0xf1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         242,
         "sys_mq_timedsend",
         "not found",
         "0xf2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         243,
         "sys_mq_timedreceive",
         "not found",
         "0xf3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         244,
         "sys_mq_notify",
         "not found",
         "0xf4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         245,
         "sys_mq_getsetattr",
         "not found",
         "0xf5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         246,
         "sys_kexec_load",
         "not found",
         "0xf6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         247,
         "sys_waitid",
         "not found",
         "0xf7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         248,
         "sys_add_key",
         "not found",
         "0xf8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         249,
         "sys_request_key",
         "not found",
         "0xf9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         250,
         "sys_keyctl",
         "not found",
         "0xfa",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         251,
         "sys_ioprio_set",
         "not found",
         "0xfb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         252,
         "sys_ioprio_get",
         "not found",
         "0xfc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         253,
         "sys_inotify_init",
         "not found",
         "0xfd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         254,
         "sys_inotify_add_watch",
         "not found",
         "0xfe",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         255,
         "sys_inotify_rm_watch",
         "not found",
         "0xff",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         256,
         "sys_migrate_pages",
         "not found",
         "0x100",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         257,
         "sys_openat",
         "(int dfd,const char * path,struct open_how * how)",
         "0x101",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         258,
         "sys_mkdirat",
         "not found",
         "0x102",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         259,
         "sys_mknodat",
         "not found",
         "0x103",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         260,
         "sys_fchownat",
         "not found",
         "0x104",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         261,
         "sys_futimesat",
         "not found",
         "0x105",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         262,
         "sys_newfstatat",
         "not found",
         "0x106",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         263,
         "sys_unlinkat",
         "not found",
         "0x107",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         264,
         "sys_renameat",
         "not found",
         "0x108",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         265,
         "sys_linkat",
         "not found",
         "0x109",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         266,
         "sys_symlinkat",
         "not found",
         "0x10a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         267,
         "sys_readlinkat",
         "not found",
         "0x10b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         268,
         "sys_fchmodat",
         "not found",
         "0x10c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         269,
         "sys_faccessat",
         "not found",
         "0x10d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         270,
         "sys_pselect6",
         "not found",
         "0x10e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         271,
         "sys_ppoll",
         "not found",
         "0x10f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         272,
         "sys_unshare",
         "not found",
         "0x110",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         273,
         "sys_set_robust_list",
         "not found",
         "0x111",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         274,
         "sys_get_robust_list",
         "not found",
         "0x112",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         275,
         "sys_splice",
         "not found",
         "0x113",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         276,
         "sys_tee",
         "not found",
         "0x114",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         277,
         "sys_sync_file_range",
         "not found",
         "0x115",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         278,
         "sys_vmsplice",
         "not found",
         "0x116",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         279,
         "sys_move_pages",
         "not found",
         "0x117",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         280,
         "sys_utimensat",
         "not found",
         "0x118",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         281,
         "sys_epoll_pwait",
         "not found",
         "0x119",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         282,
         "sys_signalfd",
         "not found",
         "0x11a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         283,
         "sys_timerfd_create",
         "not found",
         "0x11b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         284,
         "sys_eventfd",
         "not found",
         "0x11c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         285,
         "sys_fallocate",
         "not found",
         "0x11d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         286,
         "sys_timerfd_settime",
         "not found",
         "0x11e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         287,
         "sys_timerfd_gettime",
         "not found",
         "0x11f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         288,
         "sys_accept4",
         "not found",
         "0x120",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         289,
         "sys_signalfd4",
         "not found",
         "0x121",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         290,
         "sys_eventfd2",
         "(unsigned int count,int flags)",
         "0x122",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         291,
         "sys_epoll_create1",
         "not found",
         "0x123",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         292,
         "sys_dup3",
         "not found",
         "0x124",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         293,
         "sys_pipe2",
         "not found",
         "0x125",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         294,
         "sys_inotify_init1",
         "not found",
         "0x126",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         295,
         "sys_preadv",
         "not found",
         "0x127",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         296,
         "sys_pwritev",
         "not found",
         "0x128",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         297,
         "sys_rt_tgsigqueueinfo",
         "(pid_t tgid,pid_t tid,int sig,siginfo_t * uinfo)",
         "0x129",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/signal.c",
         4262
      ],
      [
         298,
         "sys_perf_event_open",
         "(struct perf_event_attr * attr,pid_t pid,struct perf_cpu cpu,int group_fd,unsigned long flags)",
         "0x12a",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/events/core.c",
         13360
      ],
      [
         299,
         "sys_recvmmsg",
         "not found",
         "0x12b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         300,
         "sys_fanotify_init",
         "not found",
         "0x12c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         301,
         "sys_fanotify_mark",
         "not found",
         "0x12d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         302,
         "sys_prlimit64",
         "not found",
         "0x12e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         303,
         "sys_name_to_handle_at",
         "not found",
         "0x12f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         304,
         "sys_open_by_handle_at",
         "not found",
         "0x130",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         305,
         "sys_clock_adjtime",
         "not found",
         "0x131",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         306,
         "sys_syncfs",
         "not found",
         "0x132",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         307,
         "sys_sendmmsg",
         "not found",
         "0x133",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         308,
         "sys_setns",
         "not found",
         "0x134",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         309,
         "sys_getcpu",
         "(unsigned * cpu,unsigned * node)",
         "0x135",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/sys.c",
         2816
      ],
      [
         310,
         "sys_process_vm_readv",
         "not found",
         "0x136",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         311,
         "sys_process_vm_writev",
         "not found",
         "0x137",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         312,
         "sys_kcmp",
         "(int pid1,int pid2,int type,unsigned long fd1,unsigned long fd2)",
         "0x138",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/kcmp.c",
         135
      ],
      [
         313,
         "sys_finit_module",
         "not found",
         "0x139",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         314,
         "sys_sched_setattr",
         "not found",
         "0x13a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         315,
         "sys_sched_getattr",
         "not found",
         "0x13b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         316,
         "sys_renameat2",
         "(int olddirfd,const char * oldpath,int newdirfd,const char * newpath,unsigned int flags)",
         "0x13c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         317,
         "sys_seccomp",
         "not found",
         "0x13d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         318,
         "sys_getrandom",
         "not found",
         "0x13e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         319,
         "sys_memfd_create",
         "(const char * name,unsigned int flags)",
         "0x13f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         320,
         "sys_kexec_file_load",
         "not found",
         "0x140",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         321,
         "sys_bpf",
         "(enum bpf_cmd cmd,union bpf_attr * attr,unsigned int size)",
         "0x141",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/bpf/syscall.c",
         6137
      ],
      [
         322,
         "sys_execveat",
         "(int dirfd,const char * pathname,char * const argv[],char * const envp[],int flags)",
         "0x142",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         323,
         "sys_userfaultfd",
         "(int flags)",
         "0x143",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         324,
         "sys_membarrier",
         "(int cmd,int flags,int cpu_id)",
         "0x144",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/sched/membarrier.c",
         627
      ],
      [
         325,
         "sys_mlock2",
         "not found",
         "0x145",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         326,
         "sys_copy_file_range",
         "not found",
         "0x146",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         327,
         "sys_preadv2",
         "not found",
         "0x147",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         328,
         "sys_pwritev2",
         "not found",
         "0x148",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         329,
         "sys_pkey_mprotect",
         "not found",
         "0x149",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         330,
         "sys_pkey_alloc",
         "(unsigned long flags,unsigned long init_val)",
         "0x14a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         331,
         "sys_pkey_free",
         "(unsigned long pkey)",
         "0x14b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         332,
         "sys_statx",
         "(int dirfd,const char * pathname,int flags,unsigned int mask,void * stx)",
         "0x14c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         333,
         "sys_io_pgetevents",
         "not found",
         "0x14d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         334,
         "sys_rseq",
         "(struct rseq_abi * rseq_abi,uint32_t rseq_len,int flags,uint32_t sig)",
         "0x14e",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/rseq.c",
         474
      ],
      [
         335,
         "sys_uretprobe",
         "not found",
         "0x14f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         424,
         "sys_pidfd_send_signal",
         "(int pidfd,int sig,siginfo_t * info,unsigned int flags)",
         "0x1a8",
         "",
         "",
         "",
         "",
         "",
         "",
         "/tmp/linux-6.17.3/kernel/signal.c",
         4065
      ],
      [
         425,
         "sys_io_uring_setup",
         "not found",
         "0x1a9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         426,
         "sys_io_uring_enter",
         "not found",
         "0x1aa",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         427,
         "sys_io_uring_register",
         "not found",
         "0x1ab",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         428,
         "sys_open_tree",
         "not found",
         "0x1ac",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         429,
         "sys_move_mount",
         "(int from_dfd,const char * from_path,int to_dfd,const char * to_path,unsigned int ms_flags)",
         "0x1ad",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         430,
         "sys_fsopen",
         "(const char * fsname,unsigned flags)",
         "0x1ae",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         431,
         "sys_fsconfig",
         "(int fs_fd,unsigned cmd,const char * key,const void * val,int aux)",
         "0x1af",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         432,
         "sys_fsmount",
         "(int fs_fd,unsigned flags,unsigned ms_flags)",
         "0x1b0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         433,
         "sys_fspick",
         "(int dfd,const char * path,unsigned flags)",
         "0x1b1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         434,
         "sys_pidfd_open",
         "not found",
         "0x1b2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         435,
         "sys_clone3",
         "not found",
         "0x1b3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         436,
         "sys_close_range",
         "(unsigned int fd,unsigned int max_fd,unsigned int flags)",
         "0x1b4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         437,
         "sys_openat2",
         "(int dfd,const char * path,struct open_how * how)",
         "0x1b5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         438,
         "sys_pidfd_getfd",
         "not found",
         "0x1b6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         439,
         "sys_faccessat2",
         "not found",
         "0x1b7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         440,
         "sys_process_madvise",
         "(int pidfd,const struct iovec * iovec,size_t n,int advice,unsigned int flags)",
         "0x1b8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         441,
         "sys_epoll_pwait2",
         "(int fd,struct epoll_event * events,int maxevents,const struct __kernel_timespec * timeout,const sigset_t * sigset,size_t sigsetsize)",
         "0x1b9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         442,
         "sys_mount_setattr",
         "(int dfd,const char * path,unsigned int flags,struct mount_attr * attr,size_t size)",
         "0x1ba",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         443,
         "sys_quotactl_fd",
         "not found",
         "0x1bb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         444,
         "sys_landlock_create_ruleset",
         "not found",
         "0x1bc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         445,
         "sys_landlock_add_rule",
         "not found",
         "0x1bd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         446,
         "sys_landlock_restrict_self",
         "not found",
         "0x1be",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         447,
         "sys_memfd_secret",
         "not found",
         "0x1bf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         448,
         "sys_process_mrelease",
         "not found",
         "0x1c0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         449,
         "sys_futex_waitv",
         "not found",
         "0x1c1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         450,
         "sys_set_mempolicy_home_node",
         "not found",
         "0x1c2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         451,
         "sys_cachestat",
         "not found",
         "0x1c3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         452,
         "sys_fchmodat2",
         "(int dfd,const char * filename,mode_t mode,int flags)",
         "0x1c4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         453,
         "sys_map_shadow_stack",
         "not found",
         "0x1c5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         454,
         "sys_futex_wake",
         "not found",
         "0x1c6",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         455,
         "sys_futex_wait",
         "not found",
         "0x1c7",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         456,
         "sys_futex_requeue",
         "not found",
         "0x1c8",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         457,
         "sys_statmount",
         "(__u64 mnt_id,__u64 mnt_ns_id,__u64 mask,unsigned int flags)",
         "0x1c9",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         458,
         "sys_listmount",
         "(__u64 mnt_id,__u64 last_mnt_id,__u64 mnt_ns_id,__u64 list[],size_t num,unsigned int flags)",
         "0x1ca",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         459,
         "sys_lsm_get_self_attr",
         "not found",
         "0x1cb",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         460,
         "sys_lsm_set_self_attr",
         "not found",
         "0x1cc",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         461,
         "sys_lsm_list_modules",
         "not found",
         "0x1cd",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         462,
         "sys_mseal",
         "(void * start,size_t len)",
         "0x1ce",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         463,
         "sys_setxattrat",
         "not found",
         "0x1cf",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         464,
         "sys_getxattrat",
         "not found",
         "0x1d0",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         465,
         "sys_listxattrat",
         "not found",
         "0x1d1",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         466,
         "sys_removexattrat",
         "not found",
         "0x1d2",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         467,
         "sys_open_tree_attr",
         "(int dfd,const char * path,unsigned int flags,struct mount_attr * attr,size_t size)",
         "0x1d3",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         468,
         "sys_file_getattr",
         "not found",
         "0x1d4",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         469,
         "sys_file_setattr",
         "not found",
         "0x1d5",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         512,
         "compat_sys_rt_sigaction",
         "not found",
         "0x200",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         513,
         "compat_sys_x32_rt_sigreturn",
         "not found",
         "0x201",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         514,
         "compat_sys_ioctl",
         "not found",
         "0x202",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         515,
         "sys_readv",
         "not found",
         "0x203",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         516,
         "sys_writev",
         "not found",
         "0x204",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         517,
         "compat_sys_recvfrom",
         "not found",
         "0x205",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         518,
         "compat_sys_sendmsg",
         "not found",
         "0x206",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         519,
         "compat_sys_recvmsg",
         "not found",
         "0x207",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         520,
         "compat_sys_execve",
         "not found",
         "0x208",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         521,
         "compat_sys_ptrace",
         "not found",
         "0x209",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         522,
         "compat_sys_rt_sigpending",
         "not found",
         "0x20a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         523,
         "compat_sys_rt_sigtimedwait_time64",
         "not found",
         "0x20b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         524,
         "compat_sys_rt_sigqueueinfo",
         "not found",
         "0x20c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         525,
         "compat_sys_sigaltstack",
         "not found",
         "0x20d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         526,
         "compat_sys_timer_create",
         "not found",
         "0x20e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         527,
         "compat_sys_mq_notify",
         "not found",
         "0x20f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         528,
         "compat_sys_kexec_load",
         "not found",
         "0x210",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         529,
         "compat_sys_waitid",
         "not found",
         "0x211",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         530,
         "compat_sys_set_robust_list",
         "not found",
         "0x212",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         531,
         "compat_sys_get_robust_list",
         "not found",
         "0x213",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         532,
         "sys_vmsplice",
         "not found",
         "0x214",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         533,
         "sys_move_pages",
         "not found",
         "0x215",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         534,
         "compat_sys_preadv64",
         "not found",
         "0x216",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         535,
         "compat_sys_pwritev64",
         "not found",
         "0x217",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         536,
         "compat_sys_rt_tgsigqueueinfo",
         "not found",
         "0x218",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         537,
         "compat_sys_recvmmsg_time64",
         "not found",
         "0x219",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         538,
         "compat_sys_sendmmsg",
         "not found",
         "0x21a",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         539,
         "sys_process_vm_readv",
         "not found",
         "0x21b",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         540,
         "sys_process_vm_writev",
         "not found",
         "0x21c",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         541,
         "sys_setsockopt",
         "not found",
         "0x21d",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         542,
         "sys_getsockopt",
         "not found",
         "0x21e",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         543,
         "compat_sys_io_setup",
         "not found",
         "0x21f",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         544,
         "compat_sys_io_submit",
         "not found",
         "0x220",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         545,
         "compat_sys_execveat",
         "not found",
         "0x221",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         546,
         "compat_sys_preadv64v2",
         "not found",
         "0x222",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ],
      [
         547,
         "compat_sys_pwritev64v2",
         "not found",
         "0x223",
         "",
         "",
         "",
         "",
         "",
         "",
         "not found",
         ""
      ]
   ]
};
